### ISSUE TITLE
Crear Index "Coming Soon"

### ISSUE THREAD

**Issue by javierbarbozam** [javierbarbozam/cortez-amarillo#5]
Crear un index con la leyenda Coming Soon para la página.

1. Imagen del libro
2. Título 'Coming Soon'
3. Redes Sociales

**Comment by Heylin-Loaiza** [comment]
Fecha de entrega: 26 de septiembre a las 3:00 pm

**Comment by javierbarbozam** [comment]
Agregar íconos de contacto
Cambiar title del index
